services:
  ydb:
    image: ghcr.io/ydb-platform/local-ydb:latest
    container_name: ydb-local
    hostname: ydb-local
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "2135:2135" # grpc TLS
      - "2136:2136" # grpc
      - "8765:8765" # ui/monitoring
      - "9092:9092" # kafka proxy
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      # - YDB_GRPC_ENABLE_TLS=true
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_KAFKA_PROXY_PORT=9092
    volumes:
      - ../ydb_data:/ydb_data
      - ../ydb_certs:/ydb_certs
    networks:
      - ydb-net

  driver:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: ydb-c-binding-dev
    platform: linux/amd64
    volumes:
      - ..:/workspaces/ydb-c-binding:cached
      - ccache-ydbc:/ccache
    working_dir: /workspaces/ydb-c-binding
    command: sleep infinity
    networks:
      - ydb-net
    environment:
      - CCACHE_DIR=/ccache
      - CCACHE_MAXSIZE=10G
      - YDB_ENDPOINT=grpc://ydb:2136
      - YDB_DATABASE=/local

networks:
   ydb-net:
     external: true
     name: ydb-net

volumes:
  ccache-ydbc:
